config/routes.rb
Kavigator::Application.routes.draw do
  devise_for :users
  resources :articles, only: [:index, :show] do
    get :feed, on: :collection, defaults: { format: :atom }
  end

  namespace :admin do
    resources :trends
    resources :keywords
    resources :users
    resources :news_sources do
      post :clear, on: :member
    end
    resources :articles do
      get :feed, on: :collection
    end
    root to: 'articles#index'
  end
  root to: 'articles#index', defaults: { archive: true }
end

app/models/trend.rb
class Trend < ActiveRecord::Base
  has_many :articles
  validates_presence_of :name, :description

  scope :active, -> { where(active: true) }
end

app/controllers/admin/trends_controller.rb
# -*- encoding: utf-8 -*-
class Admin::TrendsController < Admin::BaseController
  before_filter :find_trend, only: [:show, :edit, :update, :destroy]

  def new
    @trend = Trend.new
  end

  def create
    @trend = Trend.new(trend_params)
    if @trend.save
      redirect_to admin_trends_path, flash: { success: 'Тренд успешно создан.' }
    else
      flash.now[:error] = 'Тренд не создан'
      render :new
    end
  end

  def index
    @trends = Trend.order('active DESC, created_at DESC')
  end

  def show
  end

  def edit
  end

  def update
    if @trend.update_attributes(trend_params)
      redirect_to admin_trends_path, flash: { success: 'Тренд успешно изменен.' }
    else
      flash.now[:error] = 'Тренд не изменен.'
      render :edit
    end
  end

  def destroy
    @trend.destroy
    redirect_to admin_trends_path, flash: { success: 'Тренд успешно удален.' }
  end

  private

  def find_trend
    @trend = Trend.find(params[:id])
  end

  def trend_params
    params.require(:trend).permit(:name, :active, :description)
  end
end

app/views/admin/trends/_form.html.haml
= simple_form_for([:admin, @trend], html: { class: 'form-horizontal' }) do |f|
  = f.input :name, label: 'Имя'
  = f.input :description, label: 'Описание'
  = f.input :active, label: 'Активность'

  = f.submit 'Сохранить'

app/views/admin/trends/edit.html.haml
= content_for :action_content do
  = render 'form'

= render 'action_name', title: "Новый тренд", link: new_admin_trend_path, name: "Изменить \"#{@trend.name}\""

app/views/admin/trends/index.html.haml
= content_for :action_content do
  %table.table
    %tr
      %th Имя
      %th Статей
      %th Активность
      %th Действия
    - @trends.each do |trend|
      %tr
        %td= link_to trend.name, admin_trend_path(trend)
        %td= link_to trend.articles.count, admin_trend_path(trend)
        %td= link_to (trend.active? ? "Да" : "Нет"), admin_trend_path(trend)
        %td
          = link_to "Изменить", edit_admin_trend_path(trend)
          = link_to "Удалить", admin_trend_path(trend), method: :delete

= render 'action_name', title: "Создать новый тренд", link: new_admin_trend_path, name: "Тренды - #{@trends.count}"

app/views/admin/trends/new.html.haml
= content_for :action_content do
  = render 'form'

= render 'action_name', title: "Новый тренд", link: new_admin_trend_path, name: "Новый тренд"

app/views/admin/trends/show.html.haml
= content_for :action_content do
  %h3= @trend.name
  %small
    Статей
    = @trend.articles.count

= render 'action_name', title: "Новый тренд", link: new_admin_trend_path, name: "Новый тренд"