config/routes.rb
Kavigator::Application.routes.draw do
  devise_for :users
  resources :articles, only: [:index, :show] do
    get :feed, on: :collection, defaults: { format: :atom }
  end

  namespace :admin do
    resources :trends
    resources :keywords
    resources :users
    resources :news_sources do
      post :clear, on: :member
    end
    resources :articles do
      get :feed, on: :collection
    end
    root to: 'articles#index'
  end
  root to: 'articles#index', defaults: { archive: true }
end

app/models/article.rb
# -*- encoding: utf-8 -*-
require 'news_factory'
class Article < ActiveRecord::Base
  scope :published,   -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }

  belongs_to :news_source
  belongs_to :trend
  validates_presence_of :text, :title, :news_source_id
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  def index
    params[:published] ||= false
    @articles = ArticleFilter.filter(params, params[:published])
    @progresses = FeedProgress.active
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(article_params)
    render nothing: true
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    render nothing: true
  end

  def feed
    NewsFactory.get_news(NewsSource.active)
    redirect_to admin_articles_path
  end

  private

  def article_params
    params.require(:article).permit!
  end
end

app/controllers/articles_controller.rb
# -*- encoding: utf-8 -*-
class ArticlesController < ApplicationController
  def index
    @articles = ArticleFilter.filter(params)
    @today_news_count = Article.where('created_at > ?', Time.now.midnight).count
    @news_source = NewsSource.find_by_id(params[:source_id])
    @trend = Trend.find_by_id(params[:trend_id])
  end

  def feed
    @title = 'Новости Дагестана Кавигатор'
    @articles = ArticleFilter.filter(params)
    @updated = @articles.first.updated_at unless @articles.empty?
    respond_to do |format|
      format.html
      format.rss { redirect_to feed_articles_path(format: :atom), status: :moved_permanently }
      format.atom { render layout: false }
    end
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/views/articles/_admin_articles_block.html.haml
#admin-wrapper
  - if permitted_to?(:manage, :admin_articles)
    = form_for [:admin, article], html: { class: 'row clearfix admin_article_block' } do |f|
      .col-lg-2
        = link_to "Удалить", admin_article_path(article), method: :delete, remote: true, class: "delete_article"
        = link_to "Открепить", ungroup_admin_published_article_path(article) if defined?(nested)

      - active = article.shared ? 'label label-info' : ''
      .col-lg-3{class: active}= link_to "Поделиться", "http://multiposting.tk/message_sets/new", target: :blank, class: "share_button"
      .col-lg-3
        = link_to "Редактировать", edit_admin_article_path(article)
      .col-lg-5
        = f.select :trend_id, options_for_select(@admin_trends.map{|t| [t.name, t.id]}, article.trend_id), {include_blank: true}, class: "choosen_select", data: {remote: true, url: admin_article_path(article), method: 'patch'}
      .col-lg-3
        Прикреплено
        = f.check_box :sticky, {}, "true", "false"
      .col-lg-3
        = f.label :published, "Опубликовать"
        = f.check_box :published, {}, "true", "false"
    :javascript
      $('.choosen_select').chosen({
        allow_single_deselect: true,
        no_results_text: 'No results matched',
        width: '200px',
        placeholder_text: '\0'
      });

app/views/articles/_article.html.haml
%li.list-group-item.article(id="article_#{article.id}")
  .left
    - if article.img_url
      %a.article_image_container(href="#{article_path(article)}")
        %img.article_image(src="#{article.img_url}")
    .article_body
      = link_to article.title, article, class: 'article_title'
      %p.article_summary= article.summary

    .clearfix
  .clearfix
  = render 'article_info', article: article

app/views/articles/_article_title.html.haml
.logbook-post-title
  .left
    %h2
      = link_to article.title, article
  .right
    .date
      %time= published_date(article)
  .clearfix

app/views/articles/_discus_comment_count.html.erb
<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'kavigator'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'kavigator'; // required: replace example with your forum shortname
    var disqus_identifier = "<%= "#{article.id} #{article.created_at}"%>";
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/articles/index.html.haml
/ .articles
/   = render @articles
/   = render 'discus_comment_count'
/ #logbook-pagination
/   = will_paginate @articles
.logbook-post-title
  .left
    %h2
      = l DateTime.now, format: :ru_full_month_date
  / .right
  /   .date
  /     %time= @today_news_count
  .clearfix

%ul.list-group.articles
  = render @articles
#logbook-pagination
  = will_paginate @articles

app/views/articles/index.js.erb
$('.articles').append('<%= j render(@articles) %>');
<%- if @articles.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@articles) %>');
<% else %>
  $('.pagination').html('<p>Новости кончились.<a href="<%= articles_path %>"">Обновите страницу.</a></p>');
<% end %>

app/views/articles/show.html.haml
.logbook-post-content.detail.post.tag-panorama.tag-mountain
  = render '/articles/article_title', article: @article
  .logbook-post-single
    = @article.text.html_safe
  .logbook-post-excerpt
    .author-info
      .left#authorimg
        .logbook-img-figure
          .logbook-img-author(style="background-image:url(#{@article.news_source.image_url})")
            %span.hidden= @article.news_source.name
      .left#authorbio
        %h3
          = link_to @article.news_source.name, @article.news_source.webpage
        .website
          = link_to @article.url, @article.url
        %p.description
          = @article.news_source.description
      .clearfix
  = render 'article_info', article: @article
#logbook-disqus
  = render '/articles/disqus', article: @article