config/routes.rb
Kavigator::Application.routes.draw do
  devise_for :users
  resources :articles, only: [:index, :show] do
    get :feed, on: :collection, defaults: { format: :atom }
  end

  namespace :admin do
    resources :trends
    resources :keywords
    resources :users
    resources :news_sources do
      post :clear, on: :member
    end
    resources :articles do
      get :feed, on: :collection
    end
    root to: 'articles#index'
  end
  root to: 'articles#index', defaults: { archive: true }
end

app/models/news_source.rb
class NewsSource < ActiveRecord::Base
  validates_presence_of :name, :description
  validates :url,
            presence: true,
            uniqueness: true,
            format: %r{\A(http://|https://|\S)[a-zA-Z0-9\-\_\.]+\.[a-zA-Z]{2,3}(/\S*)?\z}i
  validates :webpage,
            presence: true,
            format: %r{\A(http://|https://)[a-zA-Z0-9\-\_\.]+\.[a-zA-Z]{2,4}(/\S*)?\z}i

  has_many :articles, dependent: :destroy
  has_many :visited_pages, dependent: :destroy

  scope :active, -> { where(active: true) }

  def clear
    articles.delete_all
    visited_pages.delete_all
  end
end

app/controllers/admin/news_sources_controller.rb
# -*- encoding: utf-8 -*-
class Admin::NewsSourcesController < Admin::BaseController
  before_filter :find_source, only: [:show, :clear, :destroy, :edit, :update]

  def index
    @news_sources = NewsSource.all
  end

  def new
    @news_source = NewsSource.new
  end

  def create
    @news_source = NewsSource.new(news_source_params)
    if @news_source.save
      redirect_to admin_news_sources_path, flash: { success: 'Источник новостей успешно создан.' }
    else
      flash.now[:error] = 'Источник новостей не добавлен.'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @news_source.update_attributes(news_source_params)
      redirect_to admin_news_sources_path, flash: { success: 'Источник новостей успешно изменен.' }
    else
      flash.now[:error] = 'Источник новостей не изменен.'
      render :edit
    end
  end

  def clear
    @news_source.clear
    redirect_to admin_news_sources_path, flash: { success: 'Статьи успешно удалены.' }
  end

  def destroy
    @news_source.destroy
    redirect_to admin_news_sources_path, flash: { success: 'Источник новостей успешно удален.' }
  end

  private

  def find_source
    @news_source = NewsSource.find(params[:id])
  end

  def news_source_params
    params.require(:news_source).permit(:name, :url, :webpage, :active, :description, :image_url, :find_helper, :ignore_helper, :greedy)
  end
end

app/views/admin/news_sources/_form.html.haml
= simple_form_for([:admin, @news_source], html: { class: 'form-horizontal' }) do |f|
  = f.input :name, label: 'Имя'
  = f.input :url, label: 'Ссылка'
  = f.input :find_helper, label: 'Поиск в пределах'
  = f.input :ignore_helper, label: 'Игнорировать'
  = f.input :description, label: 'Описание'
  = f.input :image_url, label: 'Ссылка на логотип'
  = f.input :webpage, label: 'Ссылка на страницу издания'
  = f.input :active, label: 'Активность'
  = f.input :greedy, label: 'Жадность'

  = f.submit 'Сохранить'

app/views/admin/news_sources/edit.html.haml
= content_for :action_content do
  = render 'form'

= render 'action_name', title: "Новый источник", link: new_admin_news_source_path, name: "Изменение #{@news_source.name}"

app/views/admin/news_sources/index.html.haml
= content_for :action_content do
  %table.table
    %tr
      %th Название
      %th Статей
      %th URL
      %th Действия
    - @news_sources.each do |source|
      %tr
        %td= link_to source.name, admin_news_source_path(source)
        %td= link_to source.articles.count, admin_news_source_path(source)
        %td= link_to source.url, source.url, target: "_blank"
        %td= link_to "Удалить", admin_news_source_path(source), method: :delete
        %td= link_to "Изменить", edit_admin_news_source_path(source)
        %td= link_to "Очистить", clear_admin_news_source_path(source), method: :post

= render 'action_name', title: 'Новый источник новостей', link: new_admin_news_source_path, name: "Источники новостей (#{@news_sources.length})"

app/views/admin/news_sources/new.html.haml
= content_for :action_content do
  = render 'form'

= render 'action_name', title: 'Новый источник новостей', link: new_admin_news_source_path, name: "Новый источник"

app/views/admin/news_sources/show.html.haml
= content_for :action_content do
  %h4= "Статей: #{@news_source.articles.count.to_s}"

= render 'action_name', title: 'Новый источник новостей', link: new_admin_news_source_path, name: @news_source.name