config/routes.rb
Kavigator::Application.routes.draw do
  devise_for :users
  resources :articles, only: [:index, :show] do
    get :feed, on: :collection, defaults: { format: :atom }
  end

  namespace :admin do
    resources :trends
    resources :keywords
    resources :users
    resources :news_sources do
      post :clear, on: :member
    end
    resources :articles do
      get :feed, on: :collection
    end
    root to: 'articles#index'
  end
  root to: 'articles#index', defaults: { archive: true }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/views/admin/base/_article_info.html.haml
- if permitted_to?(:manage, :admin_articles)
  %div
    %span
      %a(href="#{articles_path(source_id: article.news_source.id)}" target="_blank")
        %i.fa.fa-user
        = article.news_source.name

    .right
      %i.fa.fa-clock-o
      = published_date(article)
      .clearfix
    .clearfix
  = form_for [:admin, article], html: { class: 'admin_article_block' } do |f|
    .logbook-post-info
      .left
        %ul
          %li
            = link_to content_tag(:i,nil, class: 'fa fa-times-circle-o'), admin_article_path(article), method: :delete, remote: true, class: "delete_article google-plus", title: "Удалить"
          %li
            - if article.archive === true
              = link_to content_tag(:i,nil, class: 'fa fa-share-square-o'), admin_article_path(article), class: 'facebook edit_article_attribute_link publish_article', data: {method: :patch, attribute: "article[archive]", value: false}, title: "В неопубликованные"
            - else
              = link_to content_tag(:i,nil, class: 'fa fa-share-square'), admin_article_path(article), class: 'facebook edit_article_attribute_link publish_article', data: {method: :patch, attribute: "article[archive]", value: true}, title: "В ленту"
          %li
            = link_to content_tag(:i,nil, class: 'fa fa-edit'), edit_admin_article_path(article), class: 'twitter', title: "Редактировать"
          %li
            = link_to content_tag(:i,nil, class: 'fa fa-square'), admin_article_path(article), class: ('logbook-orange edit_article_attribute_link sticky' + (article.sticky? ? '' : ' hidden')), data: {method: :patch, attribute: "article[sticky]", value: false}, title: "Открепить"
            = link_to content_tag(:i,nil, class: 'fa fa-check-square'), admin_article_path(article), class: ('logbook-orange edit_article_attribute_link un_sticky' + (article.sticky? ? ' hidden' : '')) , data: {method: :patch, attribute: "article[sticky]", value: true}, title: "Прикрепить"
          %li
            - if article.published
              = link_to content_tag(:i,nil, class: 'fa fa-cloud-download'), admin_article_path(article), class: 'logbook-orange edit_article_attribute_link publish_article', data: {method: :patch, attribute: "article[published]", value: false}, title: "В неопубликованные"
            - else
              = link_to content_tag(:i,nil, class: 'fa fa-cloud-upload'), admin_article_path(article), class: 'logbook-orange edit_article_attribute_link publish_article', data: {method: :patch, attribute: "article[published]", value: true}, title: "  Опубликовать"
          %li
            .logbook-post-tag
              %span
                = f.select :trend_id, options_for_select(@admin_trends.map{|t| [t.name, t.id]}, article.trend_id), {include_blank: true}, class: "", data: {remote: true, url: admin_article_path(article), method: 'patch'}

        .clearfix
      .clearfix

app/views/admin/base/_social_wrapper.html.haml
#logbook-social-wrapper
  .container
    .row
      .col-lg-12
        #logbook-social-body
          .left
            %ul#nav.l_tinynav1
              %li.selected
                %a(href="/" id="link-home")
                  %i.fa.fa-home
                  %span.hidden Home
              %li{class: ('active' if params[:controller] == 'admin/articles' && (!params[:published] || params[:published] == "false") && (!params[:archive]))}
                = link_to("Новое", admin_articles_path(published: false)) if permitted_to?(:manage, :admin_articles)
              %li{class: ('active' if params[:controller] == 'admin/articles' && params[:published] == "true")}
                = link_to("Интересное", admin_articles_path(published: true)) if permitted_to?(:manage, :admin_articles)
              %li{class: ('active' if params[:controller] == 'admin/articles' && params[:archive] == "true")}
                = link_to("Лента", admin_articles_path(archive: true)) if permitted_to?(:manage, :admin_articles)
              %li{class: ('active' if params[:controller] == 'admin/trends')}
                = link_to("Тренды", admin_trends_path) if permitted_to?(:manage, :admin_trends)
              %li{class: ('active' if params[:controller] == 'admin/keywords')}
                = link_to("Слова", admin_keywords_path) if permitted_to?(:manage, :admin_keywords)
              %li{class: ('active' if params[:controller] == 'admin/news_sources')}
                = link_to("Источники", admin_news_sources_path) if permitted_to?(:manage, :admin_news_sources)
              %li{class: ('active' if params[:controller] == 'admin/users')}
                = link_to("Пользователи", admin_users_path) if permitted_to?(:manage, :admin_users)
            .clearfix
          .clearfix